language: python
sudo: required
group: deprecated-2017Q2
matrix:
  include:
  - os: linux
    dist: trusty
python: '3.5'
before_install:
    - chmod +x ./.travis/test.sh
script:
    - "./.travis/test.sh"
